### ISSUE TITLE
TestInvalidParams test has invalid assertion

### ISSUE THREAD

**Issue by activescott** [smartsheet-platform/smartsheet-csharp-sdk#106]
https://github.com/smartsheet-platform/smartsheet-csharp-sdk/blob/2fdfa045552db5db2c3d01477665aa321a95f50f/IntegrationTestSDK/EventResourcesTest.cs#L57

Just noticed `Assert.IsTrue(true);` and thought maybe this is a typo? It's also inside of a  try/catch with no real handler which seems to defeat the point of an Assertion in this test.

**Comment by timwellswa** [comment]
Scott, the statement prior to that:
```csharp
                EventResult eventResult = smartsheet.EventResources.ListEvents(0, "2.1.0An4ZapaQaOXPdojlmediSZ1WqMdi5U_3l9gViOW7ic", 10, null);
```
is invalid and should throw an exception that will execute the empty exception handler and then continue on its way. In other words, the test is to verify that invalid parameters in the call raise an exception as expected. Since an exception is raised execution stops (successful test) prior to the assert. If that assert statement is allowed to execute it means that the proceeding test failed - hence wanting the assert to always be made (always true).

**Comment by activescott** [comment]
I don't think `Assert.IsTrue(true)` would trigger a failed test which is what I understood this test is expecting (`Assert.Fail()` might be more explicit).

Anyway, do you think using the [ExpectedExceptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.expectedexceptionattribute?view=mstest-net-1.2.0) would be better here? I think it could look like this:

```CSharp
        [TestMethod]
        [ExpectedException(SmartsheetException)]
        public void TestInvalidParams_Cannot_Pass_Since_and_streamPosition()
        {
            SmartsheetClient smartsheet = new SmartsheetBuilder().SetMaxRetryTimeout(30000).Build();
            EventResult eventResult = smartsheet.EventResources.ListEvents(0, "2.1.0An4ZapaQaOXPdojlmediSZ1WqMdi5U_3l9gViOW7ic", 10, null);
        }

        [TestMethod]
        [ExpectedException(SmartsheetException)]
        public void TestInvalidParams_2()
        {
            SmartsheetClient smartsheet = new SmartsheetBuilder().SetMaxRetryTimeout(30000).Build();
            EventResult eventResult = smartsheet.EventResources.ListEvents(DateTime.Today, null, 10, true);
        }
```

Please help me understand if I'm still missing something. Or, if that makes sense to you, let me know and I'm happy to propose a PR with the change.

**Comment by timwellswa** [comment]
Ah, gotcha...yes, you are correct. 

I have never used the ExpectedExceptionAttribute...will give it a spin. Thanks for the suggestion!

**Comment by timwellswa** [comment]
Fixed in my working branch, will pull with next PR.
