### ISSUE TITLE
Unable to Search Sheet Summary

### ISSUE THREAD

**Issue by mmh474** [smartsheet-platform/smartsheet-csharp-sdk#117]
While searching for sheet summary, I'm getting the following error: 

**API call**

`SearchResult results = smartsheet.SearchResources.Search(query)`

**Exception**

`Error converting value \"summaryField\" to type 'System.Nullable'1[Smartsheet.Api.Models.SearchObjectType]'. Path 'results[0].objectType', line 1, position 56.`

**Comment by timwellswa** [comment]
Yes, I can confirm. Looks like I missed this with the SheetSummary update. Will try to get it resolved as quickly as possible.

**Comment by timwellswa** [comment]
Fixed in release 2.93.1
