### ISSUE TITLE
Double url escaping for the search api call

### ISSUE THREAD

**Issue by thijs4ef** [smartsheet-platform/smartsheet-csharp-sdk#120]
The search api sdk action does not work properly. 
In the current sdk version a space will turn into %2520, it should be %20. This is happening because the search query is escaped twice.

Escaping for the search call is done in main/Smartsheet/Api/Internal/SearchResourcesImpl.cs and in smartsheet-csharp-sdk/main/Smartsheet/Api/Internal/Util/QueryUtil.cs in the current sdk.

I created a pull request which solves this issue: https://github.com/smartsheet-platform/smartsheet-csharp-sdk/pull/116 .

Thanks!

**Comment by timwellswa** [comment]
Fixed in 2.93.2. Thanks again for the PR.
