### ISSUE TITLE
reference error

### ISSUE THREAD

**Issue by dsongatcsr** [smartsheet-platform/smartsheet-csharp-sdk#65]
While compiling master branch, I got an error from 'ShareResourcesImpl.cs', and it's because VS couldn't locate the ShareScope class. Then I've found out the class is excluded from the project.

After including it, I could compile the project.
I am wondering if you are replacing the ShareScope with some new type or somthing?

Also I've found the NUnit package is missing from the packages.config of IntegrationTestSDK project.

Cheers,
Daniel

**Comment by timwellswa** [comment]
No longer applicable.
