### ISSUE TITLE
README udpates

### ISSUE THREAD

**Issue by activescott** [smartsheet-platform/smartsheet-csharp-sdk#66]
- [x] [README.md](https://github.com/smartsheet-platform/smartsheet-csharp-sdk/blob/master/README.md) has a broken link to http://githalytics.com/smartsheet-platform/smartsheet-csharp-sdk that should be removed.
- [x] Release notes are under releases, so remove them from readme (but link to them from the readme).
- [x] Add a link/badge to the nuget page. See [lessio](https://github.com/activescott/lessio/) and [libmspack4n](https://github.com/activescott/libmspack4n) for examples.

**Comment by seweil** [comment]
Resolved, thanks for the feedback
