### ISSUE TITLE
Error while getting a Report

### ISSUE THREAD

**Issue by miyura** [smartsheet-platform/smartsheet-csharp-sdk#74]
I'm getting the following error while accessing a report

Error: 

> The value 'Smartsheet.Api.Models.Cell' is not of type 'Smartsheet.Api.Models.ReportCell' and cannot be used in this generic collection.\r\nParameter name: value

Code: 
```
            var ss = new SmartsheetBuilder()
                .SetAccessToken("XXXXXXXXXXXXXXXXXXXXXXXX")
                .Build();

            Report report = null;

            try
            {
                report = ss.ReportResources.GetReport(XXXXXXXXXXXXXXXXX,
                              new ReportInclusion[] { ReportInclusion.SOURCE_SHEETS }, 500, 1);
            }
            catch (System.Exception ex)
            {
                throw;
            }
```

**Comment by timwellswa** [comment]
This was fixed here: https://github.com/smartsheet-platform/smartsheet-csharp-sdk/commit/24ffcdddf674f6fc137bfc742e625448e6813c8e
