### ISSUE TITLE
widget positions

### ISSUE THREAD

**Issue by SniatynskyiT** [smartsheet-platform/smartsheet-csharp-sdk#84]
The widget positions that I received from SmartSheet API do not match the positions on sight. How can I get right widget positions?

**Comment by timwellswa** [comment]
Hi Taras, the XPosition, YPosition properties of the Widget contain the grid locations of the Widgets. Note that these are grid positions, not absolute locations. Also, the ordering of the Widgets is undefined, but will most likely be in the order created, not in layout order.
