### ISSUE TITLE
Proxy Server

### ISSUE THREAD

**Issue by bo55vxr** [smartsheet-platform/smartsheet-csharp-sdk#90]
Please can you add provision to provide an IWebProxy object for those who have applications within a corporate environment.

Having to create specialised IWebProxy classes and add to the .config file, whist works, is a bit haphazard.

Providing a Property / Constructor param would make things a lot cleaner

**Comment by timwellswa** [comment]
I may not be understanding your requirements. Check out the proxy example [here](https://github.com/smartsheet-platform/smartsheet-csharp-sdk/blob/master/ADVANCED.md).
