### ISSUE TITLE
Unable to Copy Rules

### ISSUE THREAD

**Issue by ryarco** [smartsheet-platform/smartsheet-csharp-sdk#98]
When using smartsheet.FolderResources.CopyFolder() or smartsheet.SheetResources.CopySheet() there is no way to include the sheet notifications as the FolderCopyInclusion enum does not have the associated `rule` and `ruleRecipients` flags. This seems to be possible using HTTP requests as documented [here](https://smartsheet-platform.github.io/api-docs/?shell#copy-folder) but appears missing from the C# API.

**Comment by ST252** [comment]
+1

**Comment by leehadassin** [comment]
+1

**Comment by timwellswa** [comment]
fixed in 2.68.3 release

**Comment by ryarco** [comment]
Many thanks! Really appreciate it!

**Comment by ryarco** [comment]
Whilst the FolderCopyInclusion.RULES, FolderCopyInclusion.RULE_RECIPIENTS options now work, they are not included as part of the FolderCopyInclusion.ALL flag. Is this intentional?

Love your work. Smartsheet is fantastic!

**Comment by timwellswa** [comment]
Yes, RULES and RULE_RECIPIENTS are not a part of ALL intentionally. ALL is being deprecated. In your code  you should specify exactly what you want to copy.
